const os = require('os')

console.log(os.EOL)
// console.log(os.constants.signals)
// console.log(os.constants.errno)
console.log(os.arch())
console.log(os.cpus())
console.log(os.endianness())
console.log(os.freemem())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.loadavg())
console.log(os.platform())
console.log(os.release())
console.log(os.tmpdir())
console.log(os.totalmem())
console.log(os.type())
const date = new Date()
console.log(date.toUTCString(), new Date(os.uptime()).toUTCString())
console.log(new Date(date - os.uptime()).toUTCString())